### ISSUE TITLE
Need a new release with <ES5 fixes

### ISSUE THREAD

**Issue by vladikoff** [dannycoates/abatar#11]
@dannycoates we need a new release of Abatar -> Able -> Express Able 
with these fixes:
https://github.com/dannycoates/abatar/commit/306e2e0d9f25d91bd972641baf3cc8cbb06803e0

Ref https://github.com/dannycoates/able/blob/master/package.json#L15

**Comment by dannycoates** [comment]
do we know this works on ancient android with this fix?

**Comment by dannycoates** [comment]
saucelabs no longer lists android 2.3 here https://saucelabs.com/rest/v1/info/browsers/webdriver

so it can't be done automatically :(
